In [1]:
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from mordred import Calculator, descriptors

In [2]:
df_cate = pd.read_csv('Catechol_smiles.csv', index_col=0)
df_cate

                                               SMILES
Cate_name
Catechol                                OC1=CC=CC=C1O
4Me-Catechol                         OC1=CC=C(C)C=C1O
4Cl-Catechol                        OC1=CC=C(Cl)C=C1O
4NO2-Catechol             OC1=CC=C([N+]([O-])=O)C=C1O
4OH-Catechol                         OC1=CC=C(O)C=C1O
4CN-Catechol                       OC1=CC=C(C#N)C=C1O
Dihydroxynaphthalene            OC1=CC2=CC=CC=C2C=C1O
4Br-Catechol                        OC1=CC=C(Br)C=C1O
4tBu-Catechol                 OC1=CC=C(C(C)(C)C)C=C1O
4F-Catechol                          OC1=CC=C(F)C=C1O
4Ph-Catechol               OC1=CC=C(C2=CC=CC=C2)C=C1O
4OCOEt-Catechol               OC1=CC(C(OCC)=O)=CC=C1O
4Bz-Catechol          OC1=CC(C(C2=CC=CC=C2)=O)=CC=C1O
4CH2OH-Catechol                     OC1=CC=C(CO)C=C1O
4OMe-Catechol                       OC1=CC=C(OC)C=C1O
3F-Catechol                          OC1=CC=CC(F)=C1O
3OMe-Catechol                       OC1=CC=CC(OC)=C1O

In [3]:
calc = Calculator(descriptors, ignore_3D = True)
df_1 = calc.pandas([Chem.MolFromSmiles(smile) for smile in df_cate['SMILES']])
display(df_1)

100%|██████████| 17/17 [00:01<00:00, 14.03it/s]

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,5.835194,5.606207,0,0,9.953960,2.193527,4.387054,9.953960,1.244245,2.980241,...,8.555837,35.908899,110.036779,7.859770,60,8,36.0,39.0,3.222222,1.861111
1,6.651690,6.355891,0,0,10.792280,2.245827,4.491654,10.792280,1.199142,3.099448,...,8.806724,37.839725,124.052429,7.297202,84,10,42.0,46.0,4.083333,2.027778
2,6.651690,6.355891,0,0,10.792280,2.245827,4.491654,10.792280,1.199142,3.099448,...,8.806724,37.839725,143.997807,10.285558,84,10,42.0,46.0,4.083333,2.027778
3,8.134854,7.731889,0,0,13.152542,2.292456,4.584911,13.152542,1.195686,3.294652,...,9.071423,40.991311,155.021858,9.688866,152,14,52.0,58.0,5.194444,2.472222
4,6.651690,6.355891,0,0,10.792280,2.245827,4.491654,10.792280,1.199142,3.099448,...,8.806724,37.839725,126.031694,8.402113,84,10,42.0,46.0,4.083333,2.027778
5,7.249407,6.952976,0,0,12.392927,2.262725,4.525450,12.392927,1.239293,3.197657,...,8.899867,39.293282,135.032028,9.002135,117,12,46.0,51.0,4.333333,2.361111
6,9.330288,8.060476,0,0,15.531532,2.370021,4.740043,15.531532,1.294294,3.426586,...,9.404838,43.148430,160.052429,8.002621,182,17,62.0,72.0,3.944444,2.638889
7,6.651690,6.355891,0,0,10.792280,2.245827,4.491654,10.792280,1.199142,3.099448,...,8.806724,37.839725,187.947292,13.424807,84,10,42.0,46.0,4.083333,2.027778
8,9.078767,8.582454,0,0,13.748763,2.348625,4.697251,13.748763,1.145730,3.390619,...,9.366917,42.993763,166.099380,6.388438,189,16,60.0,67.0,6.145833,2.527778
9,6.651690,6.355891,0,0,10.792280,2.245827,4.491654,10.792280,1.199142,3.099448,...,8.806724,37.839725,128.027358,9.144811,84,10,42.0,46.0,4.083333,2.027778
10,10.744501,9.200710,0,0,18.348875,2.335372,4.670745,18.348875,1.310634,3.564716,...,9.398561,45.522055,186.068080,7.752837,303,19,70.0,80.0,4.444444,3.138889
11,9.439677,8.869909,0,0,15.803738,2.305760,4.611519,15.803738,1.215672,3.451169,...,9.178540,43.622944,182.057909,7.915561,256,17,60.0,67.0,5.694444,3.055556
12,12.227664,10.542120,0,0,20.782029,2.350321,4.700643,20.782029,1.298877,3.691669,...,9.552155,48.223977,214.062994,8.233192,444,23,80.0,92.0,5.555556,3.583333
13,7.249407,6.952976,0,0,12.392927,2.262725,4.525450,12.392927,1.239293,3.197657,...,8.899867,39.293282,140.047344,7.780408,117,12,46.0,51.0,4.333333,2.361111
14,7.249407,6.952976,0,0,12.392927,2.262725,4.525450,12.392927,1.239293,3.197657,...,8.899867,39.293282,140.047344,7.780408,117,12,46.0,51.0,4.333333,2.361111
15,6.611250,6.419894,0,0,10.891331,2.263821,4.527642,10.891331,1.210148,3.099901,...,8.876126,37.975562,128.027358,9.144811,82,11,42.0,47.0,4.083333,2.055556
16,7.208967,7.056032,0,0,12.417439,2.284415,4.568829,12.417439,1.241744,3.198077,...,8.976009,39.435514,140.047344,7.780408,113,13,46.0,52.0,4.333333,2.388889

In [4]:
df_Cate_desc = df_1.loc[df_1.index.repeat(4)].reset_index(drop=True)
print(df_Cate_desc.info())
df_Cate_desc.head(10)

<class 'mordred._base.pandas_module.MordredDataFrame'>
RangeIndex: 68 entries, 0 to 67
Columns: 1613 entries, ABC to mZagreb2
dtypes: bool(2), float64(999), int64(337), object(275)
memory usage: 856.1+ KB
None

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,8.555837,35.908899,110.036779,7.859770,60,8,36.0,39.0,3.222222,1.861111
1,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,8.555837,35.908899,110.036779,7.859770,60,8,36.0,39.0,3.222222,1.861111
2,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,8.555837,35.908899,110.036779,7.859770,60,8,36.0,39.0,3.222222,1.861111
3,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,8.555837,35.908899,110.036779,7.859770,60,8,36.0,39.0,3.222222,1.861111
4,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,124.052429,7.297202,84,10,42.0,46.0,4.083333,2.027778
5,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,124.052429,7.297202,84,10,42.0,46.0,4.083333,2.027778
6,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,124.052429,7.297202,84,10,42.0,46.0,4.083333,2.027778
7,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,124.052429,7.297202,84,10,42.0,46.0,4.083333,2.027778
8,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,143.997807,10.285558,84,10,42.0,46.0,4.083333,2.027778
9,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.806724,37.839725,143.997807,10.285558,84,10,42.0,46.0,4.083333,2.027778

In [5]:
df_P = pd.read_csv('P_smiles.csv', index_col=0)
df_P

                                       SMILES
P_name
Dimethyl Phosphite             O=P([H])(OC)OC
Phosphonic acid                  [H]P(O)(O)=O
Phenylphosphinic Acid  [H]P(O)(C1=CC=CC=C1)=O
Phosphinic acid                [H]P([H])(O)=O

In [6]:
calc = Calculator(descriptors, ignore_3D = True)
df_2 = calc.pandas([Chem.MolFromSmiles(smile) for smile in df_P['SMILES']])
display(df_2)

100%|██████████| 4/4 [00:00<00:00,  7.00it/s]

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,3.644924,4.097495,0,0,6.898979,1.931852,3.863703,6.898979,1.149830,2.595800,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
1,2.449490,2.449490,2,0,3.464102,1.732051,3.464102,3.464102,0.866025,2.178059,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000
2,6.542301,6.236096,1,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,142.018366,8.876148,88,9,40.0,43.0,3.472222,2.111111
3,1.414214,1.414214,1,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,65.987066,10.997844,4,0,6.0,4.0,2.250000,1.000000

In [9]:
df_P_desc=pd.concat([df_2]*17,ignore_index=True)
print(df_P_desc.info())
df_P_desc.head(10)

<class 'mordred._base.pandas_module.MordredDataFrame'>
RangeIndex: 68 entries, 0 to 67
Columns: 1613 entries, ABC to mZagreb2
dtypes: bool(2), float64(828), int64(347), object(436)
memory usage: 856.1+ KB
None

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,3.644924,4.097495,0,0,6.898979,1.931852,3.863703,6.898979,1.149830,2.595800,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
1,2.449490,2.449490,2,0,3.464102,1.732051,3.464102,3.464102,0.866025,2.178059,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000
2,6.542301,6.236096,1,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,142.018366,8.876148,88,9,40.0,43.0,3.472222,2.111111
3,1.414214,1.414214,1,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,65.987066,10.997844,4,0,6.0,4.0,2.250000,1.000000
4,3.644924,4.097495,0,0,6.898979,1.931852,3.863703,6.898979,1.149830,2.595800,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
5,2.449490,2.449490,2,0,3.464102,1.732051,3.464102,3.464102,0.866025,2.178059,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000
6,6.542301,6.236096,1,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,142.018366,8.876148,88,9,40.0,43.0,3.472222,2.111111
7,1.414214,1.414214,1,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,65.987066,10.997844,4,0,6.0,4.0,2.250000,1.000000
8,3.644924,4.097495,0,0,6.898979,1.931852,3.863703,6.898979,1.149830,2.595800,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
9,2.449490,2.449490,2,0,3.464102,1.732051,3.464102,3.464102,0.866025,2.178059,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000

In [10]:
mordred_desc=pd.concat([df_Cate_desc, df_P_desc], axis=1)
mordred_desc.to_csv('mordred_desc.csv')
mordred_desc.head(10)

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
1,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000
2,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,8.590258,37.289972,142.018366,8.876148,88,9,40.0,43.0,3.472222,2.111111
3,5.835194,5.606207,0,0,9.95396,2.193527,4.387054,9.95396,1.244245,2.980241,...,4.174387,17.310771,65.987066,10.997844,4,0,6.0,4.0,2.250000,1.000000
4,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
5,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000
6,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,8.590258,37.289972,142.018366,8.876148,88,9,40.0,43.0,3.472222,2.111111
7,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,4.174387,17.310771,65.987066,10.997844,4,0,6.0,4.0,2.250000,1.000000
8,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,7.280008,29.753427,110.013281,8.462560,31,4,20.0,19.0,3.611111,1.666667
9,6.651690,6.355891,0,0,10.79228,2.245827,4.491654,10.79228,1.199142,3.099448,...,6.188264,24.179697,81.981981,11.711712,9,0,12.0,9.0,3.111111,1.000000